package com.dkit.gd2.alexconnolly;

public enum BookingMenuOptions
{
    CONTINUE, ADD_BOOKING, EDIT_BOOKING, DELETE_BOOKING, PRINT_BOOKINGS, PRINT_BOOKINGS_STUDENT, RETURN_COMPUTER, RETURN_BOOKING_LENGTH, PRINT_BOOKED_MACHINES, QUIT;
}
