package com.dkit.gd2.alexconnolly;

public enum MenuOptions
{
    CONTINUE,ADD_STUDENT, EDIT_STUDENT, ADD_BOOKING, EDIT_BOOKING, PRINT_BOOKINGS,
    PRINT_BOOKINGS_STUDENT, RETURN_COMPUTER, RETURN_BOOKING_LENGTH, PRINT_BOOKED_MACHINES, QUIT;
}
